name: Image push for master
on: 
  push:
    branches:
      - master
jobs:
  push-amd64:
    name: Image push/amd64
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        if: github.repository_owner == 'redhat-nfvpe'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push fedora-tools image
        if: github.repository_owner == 'redhat-nfvpe'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:fedora-tools
          file: fedora-tools/Dockerfile

      - name: Push fedora-nginx image
        if: github.repository_owner == 'redhat-nfvpe'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:fedora-nginx
          file: fedora-nginx/Dockerfile
